sudo: false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # Required for Python 3.7
install:
  - pip install poetry
  - poetry install -vvv
script:
  - python
  - python -m httprunner.cli hrun -v
  - python -m httprunner.cli hrun -h
  - poetry build
  - poetry runn coverage run --source=httprunner_apitest -m pytest -v
after_success:
  - poetry run coveralls

